name: Containers
on:
  workflow_dispatch:
  push:
    branches:
      - master
  workflow_call:

env:
  REGISTRY_IMAGE: ghcr.io/finnhering/julea

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List targets
        uses: docker/bake-action/subaction/list-targets@v4
        with:
          target: ubuntu

  build-container:
    name: Build Julea Containers
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
          target: ${{ fromJson(needs.prepare.outputs.targets) }}
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/bake-action@v5
        env:
          COMMIT_SHA: ${{ github.sha }}
          BASE_IMAGE_NAME: ${{ env.REGISTRY_IMAGE }}
        with:
          targets: ${{ matrix.target }}
          push: true
          files: |
            ./docker-bake.hcl