FROM ubuntu:latest

# Installiert die benötigten Pakete
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install cowsay

ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "Hello, Docker!" ]