name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
# Ausführen, wenn ein neuer Commit gepusht wird
on: [push]
jobs:
  Explore-GitHub-Actions:
    # Betriebssystem, auf dem der Job ausgeführt wird
    runs-on: ubuntu-latest
    # Schritte, die der Job ausführt
    steps:
      # Verwendung von vordefinierter Variable "github.event_name"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # Auschecken des Repository-Codes 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."