on:  
  push:
    branches:
      - master

jobs:
  build-container:
    name: Build & Publish Julea Containers
    # Angabe des Betriebssystems
    runs-on: ubuntu-latest
    
    # Angabe der Schritte, die ausgeführt werden sollen
    steps:
      # Schritt 1: Bereitstellen und auschecken der Repository 
      - name: Checkout
        # Uses gibt an welche Aktion man ausführen möchte. Es gibt eine weite reihe an offiziellen und "community" Aktionen 
        uses: actions/checkout@v4

      # Schritt 2: Authentifizieren bei der GitHub Container Registry (um Container zu pushen)
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        
        # With ermöglicht das übergeben von Parametern an die Aktion
        with:
          registry: ghcr.io
          # Es wird ein JINJA-Template verwendet, um auf (vordefinierte) variablen zuzugreifen
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Schritt 3: Bauen und Pushen des Containers
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/finnhering/julea:latest